name: Build and upload image

on:
  push:
    branches: [ "main" ]
    tags:
        - 'v*'

jobs:
  
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.36.0
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        WITH_V: true
        DEFAULT_BUMP: major
  
  publish:

    needs: build

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
      name: Check out code

    #get tag from the git hub repo

    - uses: docker/metadata-action@v4
      name: get github tag
      id: meta  
      with:
        images: salvadorm271/docker_pipeline
      run: echo ${{ steps.meta.outputs.tags }}

    - uses: mr-smithers-excellent/docker-build-push@v5
      name: Build & push Docker image
      with:
        image: salvadorm271/docker_pipeline
        tags: ${{ steps.meta.outputs.tags }}
        registry: docker.io
        dockerfile: Dockerfile
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}